// <auto-generated />
namespace Iftekhari.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTblBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTblBook));
        
        string IMigrationMetadata.Id
        {
            get { return "202306191850596_addTblBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
